config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'search#index', as: 'search'
  get '/sections', to: 'categories#sections', as: 'sections'
  get '/writers', to: 'authors#writers', as: 'writers'

  resources :authorships
  resources :authors do
    collection { get :search }
  end
  resources :categories do
    collection { get :search }
  end
  resources :comments
  resources :articles do
    collection { get :search }
  end

  root to: 'search#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_and_belongs_to_many :categories, after_add:    [ lambda { |a,c| a.__elasticsearch__.index_document } ],
                                       after_remove: [ lambda { |a,c| a.__elasticsearch__.index_document } ]
  # has_and_belongs_to_many :categories, after_add:    [ lambda { |a,c| Indexer.perform_async(:update,  a.class.to_s, a.id) } ],
  #                                      after_remove: [ lambda { |a,c| Indexer.perform_async(:update,  a.class.to_s, a.id) } ]
  has_many                :authorships
  has_many                :authors, through: :authorships
  has_many                :comments
  default_scope { order(published_on: :desc) }


  include Searchable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.page(page_index).per(page_size)
  end

  # GET /articles/search
  def search
    keyword = params[:q].to_s
    if keyword.length == 0
      return redirect_to action: :index
    end

    if keyword.length > 1
      @articles = Article.search(keyword, { type: params[:t] }).page(page_index).per(page_size).records
    else
      @msg = 'Please enter more than 1 letter.'
    end

    render action: :index
  end


  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :published_on, category_ids: [])
    end

    def page_index
      [params[:page].to_i, 1].max    
    end

    def page_size
      [params[:per_page].to_i, 10].max    
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def badge_categories(categories)
        return unless categories.present?

        categories.in_groups_of(badge_colors.size, false).map do |group|
            group.each_with_index.map do |category, index|
                link_to("<span class='badge badge-#{badge_colors[index]}'>#{category.title}</span>".html_safe, category_path(category.id), class: 'h4')
            end
        end.flatten.join(', ')
    end

    def badge_colors
        @badge_colors ||= %w(Primary Secondary Success Danger Warning Info Light Dark).map(&:downcase)
    end
end

app/views/articles/_form.html.erb
<%= form_for(article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% [:title, :content, :published_on].each do |field| %>
    <div class="form-group row">
      <%= form.label field, class: "col-sm-2 col-form-label text-right" %>
      <div class="col-sm-10">
        <% if article.class.columns_hash[field.to_s].type == :text %>
          <%= form.text_area :content, size: "90x10" %>
        <% elsif article.class.columns_hash[field.to_s].type == :date %>
          <%= form.date_select :published_on %>
        <% else %>
          <%= form.text_field field, class: 'col-sm-10' %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :category, class: "col-2 col-form-label text-right" %>
    <div class="col-10">
      <%= form.collection_select(:category_ids, Category.all, :id, :title,
      { prompt: "Make your selection from the list below (can be empty)"},
      { multiple: true, size: 8, class: "custom-select shadow rounded" }) %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-10">
      <%= form.submit class: 'btn btn-outline-info' %>
    </div>
    <% if article.persisted? %>
    <div class="col-md-2">
      <%= link_to 'View', article_url(article.id), class: 'btn btn-secondary' %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/articles/_list.html.erb
<% if @articles.present? %>

  <table class="table table-hover table-striped table-bordered">
    <thead>
      <tr>
        <th scope='col'>Title</th>
        <th scope='col'>Content</th>
        <th scope='col' class='headerSortDown text-nowrap'>Published on</th>
        <th scope='col'></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= truncate(article.content) %></td>
          <td><%= article.published_on %></td>
          <td>
            <div class='float-right'>
              <%= link_to 'Show', article , class: 'btn btn-outline-primary' %>
              <%= link_to 'Edit', edit_article_path(article) , class: 'btn btn-outline-primary' %>
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <hr />

  <nav aria-label="pagination">
    <%= paginate @articles %>
  </nav>

<% else %>
  <p class="alert alert-info">
  No documents have been found <%= @category.present? ? 'in this category' : 'by this author' %>.
  </p>
<% end %>

app/views/articles/_results.html.erb
<% if @articles.present? %>

  <div id="results">
    <% @articles.each do |article|  %>
    <div class="result">
      <h3 class="title">
      <%= link_to (article.try(:highlight).try(:title) ? article.highlight.title.join.html_safe : article.title), article_url(article.id) %>
      </h3>

      <p class="body">
      <% if article.try(:highlight).try(:abstract) %>
        <%= article.highlight.abstract.join.html_safe %>
      <% else  %>
        <%= article.try(:highlight).try(:content) ? article.highlight.content.join('&hellip;').html_safe : article.abstract %>
      <% end  %>
      </p>

      <% if comments = article.try(:highlight) && article.highlight['comments.body'] %>
      <p class="comments">
      Comments: <%= comments.join('&hellip;').html_safe %>
      </p>
      <% end  %>

      <p class="text-muted">
      <small>Category: <%= article.categories.to_sentence %></small> |
      <small>Authors: <%= article.authors.map(&:full_name).to_sentence %></small> |
      <small>Published: <%= article.published_on %></small>
      <% if article._score %>
      |
      <small>Score: <%= article._score %></small>
      <% end %>
      </p>
    </div>
    <% end %>
  </div>

  <br />

  <nav aria-label="pagination">
    <%= paginate @articles %>
  </nav>

<% else %>
  <p class="alert alert-info">
  No documents have been found <%= params[:c].present? ? 'in this category' : 'by this author' %>.
  </p>
<% end %>

app/views/articles/edit.html.erb
<%= render partial: 'breadcrumb', locals: { item: 'Editing Article' } %>

<div class="alert alert-light box-bordered" role="alert">
  <%= render 'form', article: @article %>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= controller.action_name == 'search' ? 'Search results' : 'Articles' %>

  <small class='float-right'>
    <%= link_to 'New Article', new_article_path, class: 'btn btn-outline-info' %>
    <%= link_to 'All Articles', articles_path, class: 'btn btn-outline-info' if params[:q] %>
  </small>
</h1>

<hr>

<%= form_tag search_articles_path, method: 'get' do %>
  <div class="input-group select-group">
    <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search...' %>
    <%= select_tag(:t, options_for_select(search_method_options, params[:t] || 'match'), { :class => 'custom-select input-group-addon' }) %>
  </div>
  <% if @msg.present? %>
  <div class='alert alert-danger mt-3'>
    <%= @msg %>
  </div>
  <% end %>
<% end %>

<% if @articles.present? %>
<table class="table mt-3 table-hover table-striped table-bordered">
  <thead>
    <tr>
      <th scope='col'>Title</th>
      <th scope='col'>Content</th>
      <th scope='col' class='headerSortDown text-nowrap'>Published on</th>
      <th scope='col'></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.__send__ controller.action_name == 'search' ? :each_with_hit : :each do |article, hit| %>
      <tr>
        <td><%= hit.try(:highlight).try(:title) ? hit.highlight.title.join.html_safe : article.title %></td>
        <td><%= truncate(hit.try(:highlight).try(:content) ? hit.content : article.content) %></td>
        <td><%= article.published_on.strftime('%Y-%m-%d') %></td>
        <td>
          <div class='float-right'>
            <%= link_to 'Show', article , class: 'btn btn-outline-primary' %>
            <%= link_to 'Edit', edit_article_path(article) , class: 'btn btn-outline-primary' %>
            <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<nav aria-label="pagination">
  <%= paginate @articles %>
</nav>

<% elsif params[:q].present? && params[:q].length > 1 %>
<div class='alert alert-warning mt-3'>
    No articles found with keyword <strong><%= params[:q] %></strong>
  </div>
<% end %>

app/views/articles/new.html.erb
<%= render partial: 'breadcrumb', locals: { item: 'New Article' } %>

<div class="alert alert-light box-bordered" role="alert">
  <%= render 'form', article: @article %>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="alert alert-dark">
  <div class='pull-right'>
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <%= link_to 'Back', :back %>
  </div>
</div>

<div class="alert" role="alert">
  <h4 class="alert-heading"><%= @article.title %></h4>
  <p>
    <%= raw badge_categories(@article.categories) %>
  </p>
  <p>
    <%= raw @article.content.gsub(/\r\n|\n/, '<br/>') %>
  </p>
  <hr />
  <p class="mb-0">
    <strong>Published On: </strong>
    <%= @article.published_on %>
    <strong>Author: </strong>
    <%= @article.authors.map(&:full_name).to_sentence %>
  </p>
</div>