config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'search#index', as: 'search'
  get '/sections', to: 'categories#sections', as: 'sections'
  get '/writers', to: 'authors#writers', as: 'writers'

  resources :authorships
  resources :authors do
    collection { get :search }
  end
  resources :categories do
    collection { get :search }
  end
  resources :comments
  resources :articles do
    collection { get :search }
  end

  root to: 'search#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authorships
  has_many :articles, through: :authorships
  default_scope { order(created_at: :desc) }
  
  def full_name
    [first_name, last_name].join(' ')
  end

  after_update { self.authorships.each(&:touch) }
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :set_page_size, only: [:index, :list, :show, :writers, :search]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.page(page_index).per(page_size)
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @articles = @author.articles.page(page_index).per(page_size)
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def writers
    index
  end

  # GET /authors/search
  def search
    keyword = params[:q].to_s
    if keyword.length == 0
      return redirect_to action: :index
    end

    if keyword.length > 1
      # @authors = Author.where("first_name + ' ' + last_name LIKE ?", "%" + keyword + "%").page(page_index).per(page_size)
      @authors = Author.where("first_name LIKE ? OR last_name LIKE ?", "%#{keyword}%", "%#{keyword}%") .page(page_index).per(page_size)
    else
      @msg = 'Please enter more than 1 letter.'
    end
    render action: :index
  end

  private

  def set_page_size
    @page_size = if params[:action] == 'list'
      6
    elsif params[:action] == 'writers'
      12
    else
      10
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = Author.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end

  def page_index
    [params[:page].to_i, 1].max    
  end

  def page_size
    [params[:per_page].to_i, @page_size].max    
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% [:first_name, :last_name].each do |field| %>
    <div class="form-group row">
      <%= form.label field, class: "col-sm-2 col-form-label text-right" %>
      <div class="col-sm-10">
        <% if author.class.columns_hash[field.to_s].type == :text %>
          <%= form.text_area :content, size: "90x10" %>
        <% elsif author.class.columns_hash[field.to_s].type == :date %>
          <%= form.date_select :published_on %>
        <% else %>
          <%= form.text_field field, class: 'col-sm-10' %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-sm-10">
      <%= form.submit class: 'btn btn-outline-info' %>
    </div>
  </div>
<% end %>

app/views/authors/edit.html.erb
<%= render partial: 'breadcrumb', locals: { item: 'Editing Author' } %>

<div class="alert alert-light box-bordered" role="alert">
  <%= render 'form', author: @author %>
</div>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Authors
  <small class='float-right'>
    <%= link_to 'New Author', new_author_path, class: 'btn btn-outline-info' %>
  </small>
</h1>

<hr>

<%= form_tag search_authors_path, method: 'get' do %>
  <div class="input-group">
    <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search...' %>
  </div>
  <% if @msg.present? %>
  <div class='alert alert-danger mt-3'>
    <%= @msg %>
  </div>
  <% end %>
<% end %>

<% if @authors.present? %>
<table class="table mt-3 table-hover table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col" class='headerSortDown'>Created at</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= author.created_at.strftime('%Y-%m-%d') %></td>
        <td>
          <h5 title="Articles by this author" class='float-left'><span class='badge badge-warning'><%= author.articles.size %></span></h5>
          <div class='float-right'>
            <%= link_to 'Show', author, class: 'btn btn-outline-info' %>
            <%= link_to 'Edit', edit_author_path(author), class: 'btn btn-outline-info' %>
            <%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<nav aria-label="pagination">
  <%= paginate @authors %>
</nav>

<% elsif params[:q].present? && params[:q].length > 1 %>
<div class='alert alert-warning mt-3'>
    No authors found with keyword <strong><%= params[:q] %></strong>
  </div>
<% end %>

app/views/authors/new.html.erb
<%= render partial: 'breadcrumb', locals: { item: 'New Author' } %>

<div class="alert alert-light box-bordered" role="alert">
  <%= render 'form', author: @author %>
</div>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<% if @author.present? %>

  <div class="alert alert-dark">
    <div class='pull-right'>
      <%= link_to 'Edit', edit_author_path(@author) %> |
      <%= link_to 'Back', :back %>
    </div>
  </div>

  <div class="alert alert-secondary" role="alert">
    <h4 class="alert-heading"><%= @author.full_name %></h4>
    <hr>
    <p class="mb-0">
      <strong>Updated At: </strong>
      <%= @author.updated_at.to_s %>
    </p>
  </div>

  <%= render 'articles/list' %>

<% else %>
  <h3>Author not found.</h3>
<% end %>

app/views/authors/writers.html.erb
<div id="main-list">
  <% @authors.in_groups_of(3, false) do |group| %>
  <div class="card-group">
    <% group.each do |author| %>
    <div class="card" data-id="<%= author.id %>">
      <div class="card-body">
        <h5 class="card-title"><%= link_to author.full_name, search_path({ a: author.full_name }) %></h5>
        <p class="card-text"></p>
        <h5 title="Articles by this author"><span class='badge badge-info'><%= author.articles.size %></span></h5>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

<br />

<nav aria-label="pagination">
<%= paginate @authors %>
</nav>