config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'search#index', as: 'search'
  get '/sections', to: 'categories#sections', as: 'sections'
  get '/writers', to: 'authors#writers', as: 'writers'

  resources :authorships
  resources :authors do
    collection { get :search }
  end
  resources :categories do
    collection { get :search }
  end
  resources :comments
  resources :articles do
    collection { get :search }
  end

  root to: 'search#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  default_scope { order(title: :asc) }

  has_and_belongs_to_many :articles

  after_update { self.articles.each(&:touch) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_page_size, only: [:index, :list, :show, :sections, :search]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.includes(:articles).page(page_index).per(page_size)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @articles = @category.present? ? @category.articles.page(page_index).per(page_size) : []
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sections
    index
  end

  # GET /categories/search
  def search
    keyword = params[:q].to_s
    if keyword.length == 0
      return redirect_to action: :index
    end

    if keyword.length > 1
      @categories = Category.where("title LIKE ?", "%" + keyword + "%").page(page_index).per(page_size)
    else
      @msg = 'Please enter more than 1 letter.'
    end

    render action: :index
  end

  private

  def set_page_size
    @page_size = if params[:action] == 'list'
      6
    elsif params[:action] == 'sections'
      9
    else
      10
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.where(id: params[:id])&.first
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:title)
  end

  def page_index
    [params[:page].to_i, 1].max    
  end

  def page_size
    [params[:per_page].to_i, @page_size].max    
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% [:title].each do |field| %>
    <div class="form-group row">
      <%= form.label field, class: "col-sm-2 col-form-label text-right" %>
      <div class="col-sm-10">
        <% if category.class.columns_hash[field.to_s].type == :text %>
          <%= form.text_area :content, size: "90x10" %>
        <% elsif category.class.columns_hash[field.to_s].type == :date %>
          <%= form.date_select :published_on %>
        <% else %>
          <%= form.text_field field, class: 'col-sm-10' %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-sm-10">
      <%= form.submit class: 'btn btn-outline-info' %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: 'breadcrumb', locals: { item: 'Editing Category' } %>

<div class="alert alert-light box-bordered" role="alert">
  <%= render 'form', category: @category %>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Categories
  <small class='float-right'>
    <%= link_to 'New Category', new_category_path, class: 'btn btn-outline-info' %>
  </small>
</h1>

<hr>

<%= form_tag search_categories_path, method: 'get' do %>
  <div class="input-group">
    <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search...' %>
  </div>
  <% if @msg.present? %>
  <div class='alert alert-danger mt-3'>
    <%= @msg %>
  </div>
  <% end %>
<% end %>

<% if @categories.present? %>
<table class='table mt-3 table-hover table-striped table-bordered'>
  <thead>
    <tr>
      <th scope="col" class='headerSortUp'>Title</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td>
          <h5 title="Articles in this category" class='float-left'><span class='badge badge-warning'><%= category.articles.size %></span></h5>
          <div class='float-right'>
            <%= link_to 'Show', category, class: 'btn btn-outline-info' %>
            <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-outline-info' %>
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<nav aria-label="pagination">
  <%= paginate @categories %>
</nav>

<% elsif params[:q].present? && params[:q].length > 1 %>
<div class='alert alert-warning mt-3'>
    No categories found with keyword <strong><%= params[:q] %></strong>
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render partial: 'breadcrumb', locals: { item: 'New Category' } %>

<div class="alert alert-light box-bordered" role="alert">
  <%= render 'form', category: @category %>
</div>

app/views/categories/sections.erb
<div id="main-list">
  <% @categories.in_groups_of(3, false) do |group| %>
  <div class="card-group">
    <% group.each do |category| %>
    <div class="card" data-id="<%= category.id %>">
      <div class="card-body">
        <h5 class="card-title"><%= link_to category.title, search_path({ c: category.title }) %></h5>
        <p class="card-text"></p>
        <h5 title="Articles in this category"><span class='badge badge-info'><%= category.articles.size %></span></h5>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

<br />

<nav aria-label="pagination">
<%= paginate @categories %>
</nav>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<% if @category.present? %>

  <div class="alert alert-dark">
    <div class='pull-right'>
      <%= link_to 'Edit', edit_category_path(@category) %> |
      <%= link_to 'Back', categories_path %>
    </div>
  </div>

  <div class="alert" role="alert">
    <h4 class="alert-heading"><%= @category.title %></h4>
    <hr>
    <p class="mb-0">
      <strong>Updated At: </strong>
      <%= @category.updated_at.to_s %>
    </p>
  </div>

  <%= render 'articles/list' %>

<% else %>
  <h3>Category not found.</h3>
<% end %>